//Model generated by web
class DiscussionByDiscussionIdResponse {
  String? status;
  String? message;
  Data? data;

  DiscussionByDiscussionIdResponse({this.status, this.message, this.data});

  DiscussionByDiscussionIdResponse.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  int? id;
  String? title;
  String? body;
  bool? isEdited;
  String? createdAt;
  String? updatedAt;
  int? idUser;
  int? idCourse;
  User? user;

  Data(
      {this.id,
      this.title,
      this.body,
      this.isEdited,
      this.createdAt,
      this.updatedAt,
      this.idUser,
      this.idCourse,
      this.user});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    body = json['body'];
    isEdited = json['isEdited'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    idUser = json['id_user'];
    idCourse = json['id_course'];
    user = json['User'] != null ? new User.fromJson(json['User']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['body'] = this.body;
    data['isEdited'] = this.isEdited;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    data['id_user'] = this.idUser;
    data['id_course'] = this.idCourse;
    if (this.user != null) {
      data['User'] = this.user!.toJson();
    }
    return data;
  }
}

class User {
  String? fullName;
  Null? photoProfile;

  User({this.fullName, this.photoProfile});

  User.fromJson(Map<String, dynamic> json) {
    fullName = json['fullName'];
    photoProfile = json['photoProfile'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['fullName'] = this.fullName;
    data['photoProfile'] = this.photoProfile;
    return data;
  }
}
